config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  devise_for :applicants, controllers: {
    registrations: 'applicants/registrations',
  }
  devise_for :employers, controllers: {
    registrations: 'employers/registrations'
  }
  post 'job_applications', to: 'job_applications#create', as: :job_applications

  root :to => "application#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :employer
  has_and_belongs_to_many :applicants, join_table: 'job_applications', dependent: :destroy
  validates :title, presence: true
  validates :description, presence: true

  # If employer return only their job posts. Else all posts
  def self.get_jobs(employer: nil)
    return all unless employer
    employer.jobs
  end

  def applicant_names
    applicants.map(&:full_name).uniq.join(' , ')
  end

  def employer_name
    employer.full_name
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:create]
  before_action :authenticate_employer!, only: [:create, :edit, :update, :destroy]
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.get_jobs(employer: current_employer)
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = current_employer.jobs.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    respond_to do |format|
      if @job.save
        format.html { redirect_to jobs_path, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to jobs_path, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_job
    @job = Job.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def job_params
    params.require(:job).permit(:title, :description, :employer_id)
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def get_badge(job)
    badge_type, text = current_applicant.already_applied?(job) ? ["success","Applied"] : ["info","Open"]
    "<span class='badge badge-pill badge-#{badge_type}'>#{text}</span>".html_safe
  end
end

app/views/jobs/_form.html.erb
<%= bootstrap_form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <%= render 'shared/alert', locals: {message: "Couldn't create job" }  %>
  <% end %>
  <div class="form-group">
    <%= form.text_field :title,  placeholder: 'Job Title', class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.text_area :description ,  placeholder: 'Job Description', class: 'form-control' %>
  </div>
  <%= form.hidden_field :employer_id, value: job.employer_id %>
  <div class="form-group">
    <%= form.submit "Submit Job", class: "btn btn-primary btn-block btn-lg"  %>
  </div>
<% end %>

app/views/jobs/_show.html.erb
<%= bootstrap_form_with(model: job, url: job_applications_path, method: :post) do |form| %>
  <div class="form-group">
    <%= form.text_field :title,  placeholder: 'Job Title', class: 'form-control', readonly: true  %>
  </div>
  <div class="form-group">
    <%= form.text_area :description ,  placeholder: 'Job Description', class: 'form-control', readonly: true %>
  </div>
  <% if current_employer %>
    <div class="form-group">
      <%= form.text_area :applicant_names , placeholder: 'No Applicants Yet', class: 'form-control', readonly: true %>
    </div>
  <% else %>

    <%= form.hidden_field :job_id, value: job.id %>

    <div class="form-group">
      <%= form.text_field :employer_name , class: 'form-control', readonly: true %>
    </div>
    <% unless current_applicant.already_applied?(job) %>
      <div class="form-group">
        <%= form.submit "Apply", class: "btn btn-primary btn-block btn-lg" %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/jobs/edit.html.erb
<div class="row d-flex justify-content-center">
  <div class="col-sm-4 col-sm-offset-4">
    <h1 class="text-center">Editing Job</h1>
    <hr>

    <%= render 'form', job: @job %>

    <%= link_to 'Back', jobs_path %>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="container">
  <br>
  <%= render 'shared/messages' %>

  <h1>Jobs</h1>
  <% unless applicant_signed_in? %>
    <%= link_to 'Create New Job Post', new_job_path %>
  <% end %>
  <br>
  <br>
  <% if @jobs.present? %>
    <table class="table ">
      <thead>
      <tr>
        <th > Title </th>
        <th > Show </th>
        <% if employer_signed_in? %>
          <th > Edit </th>
          <th > Destroy </th>
        <% else %>
          <th> Employer </th>
          <th > Status </th>
        <% end %>
      </tr>
      </thead>

      <tbody>
      <% @jobs.each do |job| %>
        <tr>
          <td><%= job.title %> </td>
          <td colspan="1"><%= link_to 'Show', job %></td>

          <% if employer_signed_in? %>
            <td colspan="1"><%= link_to 'Edit', edit_job_path(job) %></td>
            <td colspan="1"><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% else %>
            <td colspan="1"><%= job.employer_name %></td>
            <td colspan="1"><%= get_badge(job) %></td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    No Jobs available right now.
  <% end %>
</div>

app/views/jobs/new.html.erb
<div class="row d-flex justify-content-center">
  <div class="col-sm-4 col-sm-offset-4">
    <h1 class="text-center">New Job</h1>
    <hr>

    <%= render 'form', job: @job %>

    <%= link_to 'Back', jobs_path %>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="row d-flex justify-content-center">
  <div class="col-sm-4 col-sm-offset-4">
    <br>
    <%= render 'shared/messages' %>

    <hr>

    <%= render 'show', job: @job %>

    <%= link_to 'Back', jobs_path %>
  </div>
</div>