config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  devise_for :applicants, controllers: {
    registrations: 'applicants/registrations',
  }
  devise_for :employers, controllers: {
    registrations: 'employers/registrations'
  }
  post 'job_applications', to: 'job_applications#create', as: :job_applications

  root :to => "application#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  devise_group :user, contains: [:applicant, :employer]

  def index
    redirect_to jobs_path if helpers.user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def destroy_user_session_path
    return destroy_applicant_session_path if applicant_signed_in?
    return destroy_employer_session_path if employer_signed_in?
  end
end

app/views/application/index.html.erb
<br>
<br>

<div class="container">
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <div class="row">
        <div class="col text-center">
          <%= button_to "Signup As Employer", new_employer_registration_path, class: "btn btn-primary btn-lg", :method => :get  %>
        </div>
        <div class="col text-center">
          <%= button_to "Signup As Applicant", new_applicant_registration_path, class: "btn btn-primary btn-lg", :method => :get  %>
        </div>
      </div>
      <br>
      <br>
      <div class="row">

        <div class="col text-center">
          <%= button_to "Sign In As Employer", new_employer_session_path, class: "btn btn-primary btn-lg", :method => :get  %>
        </div>
        <div class="col text-center">
          <%= button_to "Sign In As Applicant", new_applicant_session_path, class: "btn btn-primary btn-lg", :method => :get  %>
        </div>
      </div>
    </div>
  </div>
</div>