config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  devise_for :applicants, controllers: {
    registrations: 'applicants/registrations',
  }
  devise_for :employers, controllers: {
    registrations: 'employers/registrations'
  }
  post 'job_applications', to: 'job_applications#create', as: :job_applications

  root :to => "application#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobPosts</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'Job Posts', root_path, class: 'navbar-brand' %>

    <% if user_signed_in? %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Jobs', jobs_path, class: 'nav-link', method: :get %>
        </li>
      </ul>
      <ul class="navbar-nav ml-md-auto">
        <li class="nav-item">
          <%= link_to "Sign Out (#{current_user.email})", destroy_user_session_path, class: 'nav-link', method: :delete %>
        </li>
      </ul>
    <% end %>
  </nav>
  <%= yield %>
  </body>
</html>